# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0003_auto_20160207_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systersuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='systersuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
